---
- name: Backup AWX local
  hosts: localhost
  become: false

  tasks:

    - name: Créer le dossier de backup si inexistant
      file:
        path: /var/backups/awx
        state: directory
        mode: '0755'

    - name: Lancer le backup AWX
      command: awx-backup -f /var/backups/awx
      register: backup_result

    - name: Afficher le résultat du backup
      debug:
        var: backup_result.stdout
